services:
  - type: web
    name: ap-automotores
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: "gunicorn AP_Automotores.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AP_Automotores.settings