# Generated by Django 6.0.4 on 2026-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('garante_nombre', models.CharField(max_length=100)),
                ('garante_dni', models.CharField(max_length=20)),
                ('garante_ingreso', models.DecimalField(decimal_places=2, max_digits=15)),
                ('garante_antiguedad', models.IntegerField()),
                ('garante_relacion', models.CharField(choices=[('dependencia', 'Relación de dependencia'), ('independiente', 'Trabajador independiente')], max_length=20)),
                ('garante_telefono', models.CharField(blank=True, max_length=20)),
                ('modelo_auto', models.CharField(max_length=100)),
                ('precio_auto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_cuotas', models.IntegerField()),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_ingreso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cotizacion_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
