# Generated by Django 6.0.4 on 2026-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_solicitud_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='garante_fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
